#  leave if not already part of the note
- name: Leave Docker Swarm
  docker_swarm:
    state: absent
    force: true

# join the swarm
- name: Join Swarm Worker1
  docker_swarm:
    state: join
    advertise_addr: qa-worker1
    join_token: "{{ hostvars['join_token']['value'] }}"
    remote_addrs: ["qa-manager:2377"]

# join the swarm
- name: Join Swarm Worker2
  docker_swarm:
    state: join
    advertise_addr: qa-worker2
    join_token: "{{ hostvars['join_token']['value'] }}"
    remote_addrs: ["qa-manager:2377"]
