[jenkins]
localhost

[dockerswarm]
qa-manager
qa-worker1
qa-worker2

[dockerswarm:vars]
ansible_user=jenkins
ansible_ssh_common_args='-o StrictHostKeyChecking=no'
ansible_ssh_private_key_file=~/.ssh/id_rsa
ansible_python_interpreter=/usr/bin/python3

[manager]
qa-manager

[worker]
qa-worker1
qa-worker2